import 'package:flutter/cupertino.dart';
import 'package:lolproje/Hikayeara.dart';

// ignore: must_be_immutable
class Hikayeveri extends StatefulWidget {
  int secim = 0;
  List<Ara> _bolgeler = [
    Ara(
        HikayeMetni:
            'Yordleların yurdu olan bu şehrin tam olarak nerede olduğuna dair herkesin farklı bir görüşü var; fakat pek çok ölümlü ufak, haylaz canlıların yaşadığı, ilginç ve efsunlu diyarlara giden, gözle görülmeyen yollardan bahsediyor. Bu yere kontrolsüz bir büyünün hâkim olduğunu, dikkat etmeyenlerin sayısız harikaların peşinde sürüklenip bir rüyada kaybolabileceğini söylüyorlar.Bandle Şehrinde hissedilen her şeyin, yordle olmayanlar için çok daha yoğun olduğu söyleniyor. Renkler daha parlak geliyor. Yiyecek ve içeceklerin tadı duyulardan taşıyor ve bir kez tüketilen şeyin tadı ömür boyunca unutulmuyor. Güneş sürekli altın rengi parlıyor, ırmakların suyu cam gibi berrak akıyor ve hasatlar hep bereketli oluyor. Bu rivayetlerin bazıları gerçektir belki. Belki de hiçbiri değildir. Kesin bir şey söylemek imkânsız, çünkü ziyaretçilerin anlattığı hiçbir şey birbirini tutmuyor.Kesin olan tek şey, Bandle Şehrinin ve şehir sakinlerinin zamana meydan okuması. Oraya giden fanilerden bazılarının çok daha yaşlanmış şekilde dönmesinin; çoğununsa hiç dönememesinin nedeni bu olabilir.'),
    Ara(
        HikayeMetni:
            "Mavi Alev takımadalarının güvenliğinde kurulmuş olan Bilgewater, eşi benzeri olmayan bir liman şehri. Burası çok sayıda deniz canavarı avcısının yanı sıra bir sürü liman çetesine ve bilinen dünyanın dört köşesinden gelen kaçakçılara ev sahipliği yapıyor. Bu şehirde kaşla göz arasında hem servetler kazanılıyor hem de umutlar yerle yeksan oluyor. Bilgewater adaletin pençesinden, borçlarından ya da zulümden kaçanların yeni bir başlangıç yapması için biçilmiş kaftan; çünkü şehrin çarpık çurpuk sokaklarında kimse geçmişinizle ilgilenmiyor. Yine de gün geçmiyor ki şafak vakti limanda cüzdanları tam takır, gırtlakları kesilmiş halde yüzen zavallılar bulunmasın...Muazzam tehlikelerle dolu Bilgewater yasa ve ahlak prangalarıyla kısıtlanmadığından sayısız fırsata ev sahipliği yapıyor. Hextech silahlarından tutun da yerel suç baronlarının desteğine kadar, Bilgewater'da satın alamayacağınız şey yok sayılır; siz paradan haber verin yeter.Son “yağmacı kral”ın ortadan kalkmasıyla Bilgewater bir geçiş dönemine girdi. Önde gelen kaptanlar, şehrin geleceğine karar vermeye çalışıyor. Ama denize açılmaya elverişli gemiler ve onları yüzdürecek mürettebat olduğu sürece, Bilgewater Runeterra'nın en renkli ve en çok bağlantıya sahip şehri olmaya devam edecek."),
    Ara(
        HikayeMetni:
            "Prestijli bir askeri geçmişe sahip olan kudretli ve düzenli Demacia Krallığı'nın halkı, her zaman adalet, onur ve görev bilincine büyük önem vermiştir ve kültürel mirasıyla gurur duyar. Ancak tüm bu yüce prensiplere rağmen, büyük ölçüde kendine yeten bu ülke son yüzyıllarda giderek daha da dışarıya kapalı bir hale gelmiştir.Günümüzde Demacia karışıklıklarla boğuşmaktadır.Başkent Büyük Demacia Şehri, Rün Savaşlarının dehşetinden kaçanlar için bir sığınak olarak, petrisit üstüne inşa edilmiştir. Bu tuhaf beyaz taş, büyü enerjisini soğurur. Kraliyet ailesi şehrin dışında kalan kasabaların, köylerin, ormanların ve zengin mineral kaynaklarına sahip dağların savunmasını hep buradan yürütmüştür.Ancak Kral Jarvan III'ün ani ölümünün ardından, diğer soylu aileler kralın tek vârisi genç Prens Jarvan'ın tahta çıkışını henüz onaylamış değil.Sıkı sıkıya savunulan sınırların ötesinde yaşayanlara yönelik kuşku hiç durmadan artarken, çoğu eski müttefik bu çalkantılı dönemlerde güvende kalmak için başka kapıları aşındırmaya başladı bile. Hatta bazıları Demacia'nın altın çağının artık geride kaldığını ve eğer halkı, değişen dünyaya ayak uyduramazsa (ki çoğu kişi bunun mümkün olmadığını düşünmektedir) krallığın çöküşünün kaçınılmaz olduğunu bile fısıldıyor.Dünyadaki tüm petrisit bir araya gelse bile Demacia'yı kendisinden koruması mümkün olamaz."),
    Ara(
        HikayeMetni:
            "Freljord, sakinlerinin savaşçı olarak doğduğu ve büyük zorluklara göğüs gerdiği, sert doğa koşullarına sahip, acımasız bir bölge.Son derece gururlu ve bağımsızlıklarına düşkün olan Freljord kabilelerini şekillendirmiş kadim gelenekleri bilmeyen diğer Valoran halkları onları yabani, kaba saba ve “medeniyetsiz” bulur. Binlerce yıl önce Avarosa, Serylda ve Lissandra adında üç kız kardeşin kurduğu ittifak, onlar bunun farkında olmasa da tüm Runeterra'yı tehdit eden bir savaşla parçalandığında kuzey toprakları kaosa ve neredeyse bitmez bir kışa gömülmüş. Şimdi bu bölgede liderliği sadece buzun ve ateşin tahrip edemediği, olağan dışı meziyetlere sahip fanilerin hak ettiği ya da başarabileceği düşünülüyor.Buz Muhafızlarının tüm çabalarına rağmen eski ilahları, gizemli yeti halkını ve huzursuz ruh gezgini şamanları anlatan efsaneler hâlâ dilden dile dolaşıyor. Kışın Pençesi'nin akıncıları gezindikleri alanı her geçen yıl biraz daha genişleterek güneyde Demacia'nın, doğudaysa Noxus'un sınırlarını zorluyor. Sonunda, daha barışçıl bir gelecek isteyen pek çok dağınık kabile Avarosaların genç kraliçesi Ashe'e sadakat yemini etmeye başladı.Yine de gidişat hiç iyi görünmüyor. Savaşın Freljord'a dönmekte olduğu kesin ve ondan kimse kaçamayacak."),
    Ara(
        HikayeMetni:
            "Bu lanetli ülke bir zamanlar asil ve aydın bir uygarlığın yurduymuş. Elçileri ve müttefikleri buraya Kutlu Adalar dermiş. Fakat bin yıldan uzun süre önce yaşanan benzeri görülmemiş bir sihir felaketi ruhlar âlemiyle maddi âlem arasındaki sınırı yıkarak bu iki dünyayı birbirine karıştırmış... ve canlı varlıkların bir anda sonunu getirmiş.Artık adalar, Kara Sis denen ve asla dağılmayan kötücül bir dumanın içinde hapis. Toprak ise kara büyülerle yozlaşmış. Bu kasvetli kıyılara ayak basmaya cüret eden ölümlülerin yaşam gücü yavaş yavaş çalınırken ölülerin huzursuz ve doymak bilmez ruhlarını da kendilerine çekiyorlar.Sis'in içinde ölenler hortlağa dönüşüp sonsuza dek bu kâbus gibi yerde gezinmeye mahkûm oluyor. Daha da kötüsü, Gölge Adalar'ın gücü her geçen yıl artıyor ve Sis'in en güçlü hayaletleri Runeterra'nın daha da uzak yerlerine kadar ulaşabiliyor."),
    Ara(
        HikayeMetni:
            "Kâinatın ortaya çıkışıyla birlikte feryat figan varlık bulan Hiçlik, kâinatın ötesindeki bilinmez yokluğun beden bulmuş hâli gibidir. Bu doyumsuz güç, efendileri olan gizemli Gözcüler nihai felaket zamanını bildirene kadar çağlardan beri süren bir bekleyiştedir.Hiçlik'in gücünün temas ettiği faniler, ebedi gerçek dışılığa tanık olarak ıstırap içinde kıvranır ve bu ıstırap en sağlam iradeyi bile yerle bir edebilir. Hiçlik'in doğal olmayan sakinleri genellikle sınırlı zekâya sahip olsalar da ortak bir amaçla yanıp tutuşur: Runeterra'nın dört bir yanının tamamen karanlığa gömülmesini sağlamak."),
    Ara(
        HikayeMetni:
            "Hırçın denizlerle çevrili olan Ionia, çoğu kişinin İlk Diyar olarak adlandırdığı devasa bir takımadaya yayılmış ve birbiriyle ittifak halinde pek çok eyaletten oluşuyor. Ionia kültürü çok eski zamanlardan bu yana her şeyde dengeyi bulma amacıyla şekillendiğinden, maddi âlem ve ruhlar âlemi arasındaki sınır burada (özellikle yabani ormanlarda ve dağlık bölgelerde) çok daha ince.Bu bölgelerin efsunlarının sağı solu belli olmasa da, yaratıkları cinli perili ve tehlikeli olsa da pek çok Ionia'lı yüzyıllar boyu bolluk içinde yaşadı. Savaşçı keşişler, eyaletlerin milisleri ve hatta Ionia'nın kendisi halkı korumaya fazlasıyla yetiyordu.Ama bu durum on iki yıl önce, Noxus İlk Diyar'a saldırdığında sona erdi. Noxus'un bitmek tükenmek bilmeyen orduları Ionia'yı tarumar etti ve ancak yıllar sonra, çok büyük bedeller karşılığında yenilebildiler.Ionia şimdi huzursuz bir barış döneminde. Savaşa verilen farklı tepkiler bölge halkını parçaladı. Shojin keşişleri ve Kinkou tarikatı gibi gruplar dışarıya kapanmayı, savaş karşıtlığını ve kırsal geleneklere dönülmesini öğütlüyor. Navori Kardeşliği ve Gölge Tarikatı gibi daha radikal oluşumlarsa Noxus'tan intikam alabilecek, uluslaşmış bir ülke kurulabilmesi için bölgede bulunan sihrin silah olarak kullanılmasını talep ediyor.Ionia'nın kaderi, bozmaya pek az kişinin istekli olduğu çok hassas bir dengede duruyor. Ancak ayaklarının altında bir şeylerin huzursuz huzursuz kımıldandığını herkes seziyor."),
    Ara(
        HikayeMetni:
            "Element büyüleri alanındaki ustalığıyla tanınan Ixtal, Shurima İmparatorluğu'na katılan ilk bağımsız uluslardan biriydi. Tabii batıya doğru göçerek aralarında Buhruların, görkemli Helia'nın ve Targonlu münzevilerin de bulunduğu uygarlıkların kurulmasına olanak sağlayan halklardan biri olan Ixtali'ler aslında çok daha eski bir kültür. Yükseliş'e ilk erenlerin ortaya çıkmasında büyük rol oynamış olmaları da çok olası.Ancak Ixtal büyücüleri Hiçlik'ten ve daha sonra darkinlerden korunmak için komşularından uzaklaşıp vahşi doğayı bir zırh gibi çevrelerine kuşandılar. Kayıpları zaten çok büyük olduğundan, kendilerini ellerinde kalan azıcık şeyi koruma altına almaya adadılar.Binlerce yıldır ormanın derinliklerinde, dünyadan yalıtılmış haldeki gelişkin bir arkoloji, yani devasa tek bir binadan oluşan şehir olan Ixaocan artık dış etkilerden çoğunlukla uzak. Kutlu Adalar'ın mahvoluşuna ve ardından çıkan Rün Savaşlarına uzaktan tanıklık etmiş olan Ixtali'ler, Runeterra'nın tüm diğer halklarına sonradan görme özentiler olarak bakıyor ve güçlü büyülerini yabancıları kendilerinden uzak tutmakta kullanıyor."),
    Ara(
        HikayeMetni:
            "Noxus dehşetli bir ünü olan güçlü bir imparatorluk. Sınırlarının dışında yaşayanlar Noxus'u topraklarını genişletme ateşiyle yanıp tutuşan, zalim, tehditkâr bir ülke olarak görüyor. Fakat savaşçı görünümünün altında, halkın becerilerine saygı duyulduğu ve bunların geliştirildiği, alışılmadık derecede kapsayıcı bir toplum yapısı yatıyor.Noxii'ler bir zamanlar vahşi barbar kavimlermiş, ta ki artık ülkelerinin kalbi olan kadim şehre saldırana kadar. Her yanları tehditlerle çevriliymiş. Düşmanlarına şiddetle saldırarak sınırlarını her geçen yıl genişletmişler. Bu hayatta kalma mücadelesi çağdaş Noxus'luları son derece gururlu ve güce her şeyden çok önem veren bir halk yapmış. Ama bu güç farklı şekillerde zuhur edebilir.İşinde gereken başarıyı gösteren herkes hangi sosyal sınıfa mensup olduğuna, nereden geldiğine ve maddi durumuna bakılmadan yüksek mevkilere gelebiliyor. Büyü yapabilenler büyük saygı görüyor ve özel yeteneklerinin geliştirilip imparatorluk yararına kullanılabilmesi için özellikle (hatta imparatorluk sınırları dışında) aranıp bulunuyor.Bu liyakat temelli sistem idealine karşın, köklü ve soylu aileler hâlâ imparatorlukta azımsanamayacak bir güce sahip. Bu yüzden de Noxus'un en büyük düşmanlarının dışarıda değil içeride olduğundan korkanlar var."),
    Ara(
        HikayeMetni:
            "Piltover gelişimin dur durak bilmediği, her an büyüyen ve itibarı her gün biraz daha artan bir şehir. Valoran'ın kültürel başkenti sayılan şehirde sanat, zanaatkârlık, ticaret ve ilericilik; etle tırnak gibi bir arada yaşıyor. Şehir gücünü askeri kuvvetten değil, ticaret ve ileri görüşlülük çarklarının tıkır tıkır işlemesinden alıyor. Zaun'un üzerinde yükselen yamaçlara kurulu Piltover, okyanusa tepeden bakıyor; devasa deniz kapılarından geçen gemiler, buraya dünyanın dört bir yanından mallar getiriyor. Şehrin akıl almaz bir ivmeyle büyümesinin altında, bu maddi zenginlik yatıyor. Piltover, eskiden beri servetler kazandıran ve hayallerin gerçek olduğu bir şehir olarak kendini yeniden keşif ve inşa etmesiyle ünlü. Çiçeği burnunda tacir zümresi, akıl almaz girişimlerle gelişime fon sağlıyor; büyük sanatsal projelere, akla hayale gelmez hextech araştırmalarına ve iktidarlarına adanmış mimari abidelere destek veriyor. Gelişen hextech ilmine ilgi duyup şehre akın eden mucitler sayesinde, Piltover dünyanın en becerikli zanaatkârları için her geçen gün daha büyük bir cazibe merkezine dönüşüyor."),
    Ara(
        HikayeMetni:
            "Shurima imparatorluğu bir zamanlar koskoca bir kıtaya yayılmış olan çok zengin ve güçlü bir uygarlıktı. Unutulmuş çağlarda Yükseliş'e Ermişler Ordusu'nun kudretli ilah savaşçılarının kurduğu imparatorluk güneyin dağınık halklarını birleştirerek onları kalıcı bir barışa zorlamıştı.Pek baş kaldıran olmamıştı. Kaldıranlar da lanetli Icathia halkı gibi acımasızca ezilmişlerdi.Fakat birkaç yüz yıl süren genişleme ve bolluktan sonra Shurima'nın son imparatorunun Yükseliş ritüeli başarısızlığa uğrayınca imparatorluğun başkenti yerle bir oldu ve eski görkemini anlatan hikâyeler masala dönüştü. Şimdilerde Shurima çölünün göçebe sakinleri, bu acımasız diyarda sırf hayatta kalabilmek için ekmeklerini taştan çıkarıyor. Kimileri sayısı bir elin parmaklarını geçmeyen vahaları korumak için kaleler kurmuş, kimileri de içlerinde gömülü olduğuna inandıkları defineleri bulmak için sahipleri çoktan unutulup gitmiş yeraltı mezarlarına dalmış. Paralı askerlik yapan, hizmetlerini verip ücretlerini aldıktan sonra geldikleri kanunsuz ve çorak topraklara dönenler de var.Ama yine de bazıları, eski ihtişamlı günlere dönecekleri günlerin hayaliyle yaşıyor. Hatta son zamanlarda, çölün merkezinden gelen bazı fısıltılar kabileleri heyecana boğdu. Söylentilere göre imparatorları Azir geri dönmüş ve liderliğiyle önlerinde yeni, harikulade bir çağ açacakmış."),
    Ara(
        HikayeMetni:
            "Targon Dağı, eşi benzeri görülmemiş heybette sıradağlar arasından göklere yükselen güneşli kayalıklarıyla, Runeterra'nın en yüksek zirvesidir. Medeniyetten çok uzakta, her anlamda ücra olan bu dağa, emelinde en kararlı olanlar dışında kimsenin ulaşması mümkün değildir. Targon Dağı efsanelerle birlikte anılır ve efsaneleşmiş her mekân gibi hayalperestlerin, divanelerin ve serüven peşinde koşanların umut ışığına dönüşmüştür. Bazı mangal yürekliler dağa tırmanmaya bile kalkışır; kimi bilgeliğe ve aydınlanmaya ulaşmaktan, kimi şan şeref hevesinden, kimi de kalplerine işlemiş olan zirveyi kendi gözleriyle görme arzusundan güç alır. Bu tırmanışı tamamlamak neredeyse imkânsızdır ve birkaç gözü pek tırmanışçı zirveye ulaşmayı başarsa bile, kimse zirvede gördükleriyle ilgili tek kelime etmez. Dönenlerden bazılarının gözlerinde tekinsiz, boş bakışlardan fazlası olmaz. Bazıları ise pek az faninin idrak edebileceği kaderlere ve insanüstü güçlere sahip dünya dışı Suretlerle bütünleşerek, tanınmayacak kadar değişmiş halde geri döner."),
    Ara(
        HikayeMetni:
            "Bir yeraltı yerleşimi izlenimi uyandıran Zaun, aslında Piltover'ın altındaki derin kanyon ve vadilerde uzanan, geniş mi geniş bir alt şehir. Güneş ışınları Zaun'a zar zor ulaşırken, şehre vuran azıcık ışık da örümcek ağı gibi uzanan, paslanmış boruların sızdırdığı dumanın filtresinden geçip, fabrikaları andıran binalarının isli camlarından yansıdıktan sonra zemine varabiliyor. Bir zamanlar tek vücut olan Zaun ve Piltover, artık ayrı ama bir o kadar da birbirine bağımlı iki toplum. Zaun, varlığını sonsuz ve puslu bir alacakaranlığa mahkûm hâlde sürdürmesine rağmen, enerjik insanları ve zengin kültürüyle her gün daha fazla ilerliyor. Piltover'ın refahından nasiplenerek gelişirken, yukarıdaki şehrin karanlık bir yansımasını andırıyor. Piltover'a gelen malların birçoğu dönüp dolaşıp Zaun'un kara borsalarında yer alıyor ve onların denetimlerinden bunalan hextech mucitleri, tehlikeli araştırmalarına Zaun'un kucak açtığını görüp seviniyor. Zaun'un pek çok bölgesi, her tür dengesiz teknolojinin kontrolden yoksun şekilde geliştirildiği başıboş sanayisiyle zehirli bir kirliliğin esiri olmuş durumda ve tehlikelerle dolu. Şehrin alt mahallelerinde nereye baksanız zehirli atıklarla dolu durgun dereler görürsünüz; ama Zaun halkı buralarda bile yaşayıp ilerlemenin bir yolunu bulur."),
  ];

  String getHikaye() {
    return _bolgeler[secim].HikayeMetni;
  }

  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    throw UnimplementedError();
  }
}
